### ISSUE TITLE
cannounce玩家连接游戏没有声音提示。

### ISSUE THREAD

**Issue by hkthomas** [fbef0102/L4D1_2-Plugins#14]
wav文件是存在的，使用指令，sm_playsnd **.wav，游戏内客户端也可以听到声音，可以修复一下吗，谢谢 :)

**Comment by fbef0102** [comment]
剛才測試
玩家連線進來有聲音提示

請確認有指令正確寫入

// 地圖載入30內忽略連線音效
sm_ca_mapstartnosound "30.0"

// Plays a specified (sm_ca_playsoundfile) sound on player connect
sm_ca_playsound "1"

// Sound to play on player connect if sm_ca_playsound = 1
sm_ca_playsoundfile "ambient\alarms\klaxon1.wav"
