### ISSUE TITLE
l4d_tankhelper 丢出WITCH服务器崩溃。

### ISSUE THREAD

**Issue by hkthomas** [fbef0102/L4D1_2-Plugins#15]
测试环境: L4D1 ，windows+linux，SM 1.10，其他感染者可以正常被丢出，一旦丢出witch，服务器窗口将立即消失。

left4dead\logs
left4dead\addons\sourcemod\logs
没有任何报错信息产生。

原版的插件这样更改可以正常工作，但是witch直接出现在玩家身后。
`CheatCommand(thetank, "z_spawn", "witch"); `

![image](https://uploadbeta.com/share-image/hCe)

**Comment by fbef0102** [comment]
已更新[1.4版本](https://github.com/fbef0102/L4D1_2-Plugins/tree/master/l4d_tankhelper)

已知的問題:
目前蹲下狀態的witch無法像其他特感一樣丟出去
只支援**L4D2 站著的witch**能被丟出去
有待以後技術加強在做修正

`

> CheatCommand(thetank, "z_spawn", "witch");

這個指令會直接把witch生在tank準心指向的位置
也是可但是不真實

**Comment by hkthomas** [comment]
是的，所以站立的witch被丢出来会导致服务器直接崩溃。

**Comment by fbef0102** [comment]
2022/3/5 更新

在下載試試看會不會崩潰 (目前只有站立的witch能被丟出去)
謝謝

**Comment by hkthomas** [comment]
刚测试了一下，还是一样的，丢出了站立的witch，然后崩溃。

**Comment by fbef0102** [comment]
加steam 66519185
測試

**Comment by hkthomas** [comment]
这个是什么。

**Comment by fbef0102** [comment]
https://steamcommunity.com/id/HarryPotter_TW/

**Comment by hkthomas** [comment]
好的，那个数字ID搜索不到好友。

**Comment by hkthomas** [comment]
1.4完美工作，谢谢！ :)

**Comment by fbef0102** [comment]
[更新v1.6 ](https://github.com/fbef0102/L4D1_2-Plugins/tree/master/l4d_tankhelper)
Tank能丟出去Witch拋物線飛行 (一二代都能運作)
需要安裝[Actions](https://forums.alliedmods.net/showthread.php?t=336374)
