### ISSUE TITLE
l4d_votes_5.sp编译错误

### ISSUE THREAD

**Issue by RJCooLEST** [fbef0102/L4D1_2-Plugins#16]
4 error
Compiling l4d_votes_5.sp...
SourcePawn Compiler 1.11.0.6825
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2021 AlliedModders LLC

l4d_votes_5.sp(172) : error 147: new-style declarations are required
l4d_votes_5.sp(868) : error 147: new-style declarations are required
l4d_votes_5.sp(964) : error 147: new-style declarations are required
l4d_votes_5.sp(1101) : error 147: new-style declarations are required
和一些警告，目前使用已上传的插件没有问题。

**Comment by fbef0102** [comment]
使用編譯器版本1.10
