### ISSUE TITLE
ask multislot

### ISSUE THREAD

**Issue by alfari24** [fbef0102/L4D1_2-Plugins#18]
Sir,
I use multislot for 20 players, but when finale maps not all players can be carried on a ship, helicopter or plane.

only 4 or 5 players can be carried by ship, helicopter or plane. others are left behind or die.

**Comment by fbef0102** [comment]
This is classic 4+ survivors bug in left 4 dead

There are many solutions you can search, here is the best solution (I'm using now)

https://forums.alliedmods.net/showpost.php?p=2726779&postcount=38

**Comment by alfari24** [comment]
thank you sir
