### ISSUE TITLE
多特插件的卡特问题

### ISSUE THREAD

**Issue by wjingwei** [fbef0102/L4D1_2-Plugins#2]
多特插件如果在下一章节加载的时候，有玩家掉线了就会卡特，需要处死全部玩家重来才会刷特，如何修复这个问题。

**Comment by fbef0102** [comment]
1. 甚麼是卡特?

2. 使用最新版本的多特感v2.4.3插件?

**Comment by wjingwei** [comment]
> 1. 什么是卡特？
> 2. 使用最新版本的多特感v2.4.3插件？

卡特就是不刷特感，当下一章节有玩家在加载的时候退出时会有几率发生，不刷特感了需要团灭一次才会恢复正常，插件版本是最新的v2.4.3

**Comment by fbef0102** [comment]
try this one
[l4dinfectedbots v2.4.4 beta.zip](https://github.com/fbef0102/L4D1_2-Plugins/files/5486236/l4dinfectedbots.v2.4.4.beta.zip)

**Comment by wjingwei** [comment]
> try this one
> [l4dinfectedbots v2.4.4 beta.zip](https://github.com/fbef0102/L4D1_2-Plugins/files/5486236/l4dinfectedbots.v2.4.4.beta.zip)

好的，我会在这几天测试

**Comment by wjingwei** [comment]
> try this one
> [l4dinfectedbots v2.4.4 beta.zip](https://github.com/fbef0102/L4D1_2-Plugins/files/5486236/l4dinfectedbots.v2.4.4.beta.zip)

抱歉，因为这两天服务器被攻击，我只测试了一晚上，让他们加载的时候退出，目前没发现卡特的现象，后面的测试我帮不了你了

**Comment by fbef0102** [comment]
沒關係，繼續等

**Comment by wjingwei** [comment]
> 没关系，继续等

这几天确实是没有出现卡特的现象了，暂时还没发现其他问题
