### ISSUE TITLE
infectedbots多次团灭后第一波特感刷新时间问题

### ISSUE THREAD

**Issue by SuperLeePie** [fbef0102/L4D1_2-Plugins#20]
问题出现在多次团灭后，第一波特感的刷新并不是按照l4d_infectedbots_initial_spawn_timer的设置时间的时间刷出的，而是离开安全区域后立即刷出。这问题出现在三方图的几率较大比如yama m2 m3，也能出现在官方图中，比如c2m2

**Comment by SuperLeePie** [comment]
疑似与团灭时特感数量有关，团灭时特感数量较多的话出门第一波秒刷的概率会很大

**Comment by fbef0102** [comment]
試試看這個版本

[l4dinfectedbots.zip](https://github.com/fbef0102/L4D1_2-Plugins/files/9448343/l4dinfectedbots.zip)

**Comment by SuperLeePie** [comment]
好的，我已经测试过了，目前关于多次团灭后第一波特感的刷新时间确实正常了。还有一个bug是以往的版本都存在的，就是在l4d_infectedbots_coordination 1的情况下，会有小概率地打完某一波特感后插件停止刷特，整个章节不会再出现任何特感，此时如果想要让该插件继续工作，得通过一些手动创建特感的插件任意创建出一只特感后，插件才会继续工作

**Comment by SuperLeePie** [comment]
十分感谢，目前的确没有问题了
