### ISSUE TITLE
关于l4d_infectedbots_coordination 1 刷特模式下存在的问题

### ISSUE THREAD

**Issue by SuperLeePie** [fbef0102/L4D1_2-Plugins#21]
特感刷新的总数量往往小于l4d_infectedbots_max_specials 所设定的值，这种情况往往发生在出安全区域后的第一波刷新，于后的每一波刷新都往往不能保证总数量等于l4d_infectedbots_max_specials，如果通过ForcePlayerSuicide的办法来处死所有特感，则下一波刷新的数量大概率才会等于l4d_infectedbots_max_specials设定的 （实际我不清楚这是bug还是这插件预期的设定）

**Comment by fbef0102** [comment]
是bug
但我自身測試沒有遇過
還在研究

**Comment by SuperLeePie** [comment]
以下是我使用该插件时的具体操作，希望能帮助您复现bug

①我在源码内注释掉了AutoExecConfig(true, "l4dinfectedbots");以阻止插件生成cfg（我个人认为方便管理和游戏中途改变设置的操作）
②这是我对该插件cvar的设定

l4d_infectedbots_add_commonlimit "0"


l4d_infectedbots_add_commonlimit_scale "1"


l4d_infectedbots_add_specials "0"


l4d_infectedbots_add_specials_scale "1"


l4d_infectedbots_add_tankhealth "500"


l4d_infectedbots_add_tankhealth_scale "1"


l4d_infectedbots_add_tanklimit "0"


l4d_infectedbots_add_tanklimit_scale "1"


l4d_infectedbots_adjust_commonlimit_enable "0"


l4d_infectedbots_adjust_reduced_spawn_times_on_player "0"


l4d_infectedbots_adjust_spawn_times "0"


l4d_infectedbots_adjust_tankhealth_enable "0"


l4d_infectedbots_allow "1"


l4d_infectedbots_announcement_enable "0"


l4d_infectedbots_boomer_limit "3"


l4d_infectedbots_charger_limit "3"


l4d_infectedbots_coop_versus "0"


l4d_infectedbots_coop_versus_announce "0"


l4d_infectedbots_coop_versus_human_ghost_enable "0"


l4d_infectedbots_coop_versus_human_light "0"


l4d_infectedbots_coop_versus_human_limit "0"


l4d_infectedbots_coop_versus_join_access "-1"


l4d_infectedbots_coop_versus_tank_playable "0"


l4d_infectedbots_coordination "1"


l4d_infectedbots_default_commonlimit "30"


l4d_infectedbots_default_tankhealth "4000"


l4d_infectedbots_hunter_limit "3"


l4d_infectedbots_infhud_announce "0"

l4d_infectedbots_infhud_enable "0"


l4d_infectedbots_initial_spawn_timer "20"


l4d_infectedbots_jockey_limit "3"


l4d_infectedbots_lifespan "30"


l4d_infectedbots_max_specials "18"


l4d_infectedbots_modes ""


l4d_infectedbots_modes_off ""


l4d_infectedbots_modes_tog "0"


l4d_infectedbots_safe_spawn "0"


l4d_infectedbots_sm_zs_disable_gamemode "6"


l4d_infectedbots_smoker_limit "3"


l4d_infectedbots_spawn_range_final "0"


l4d_infectedbots_spawn_range_max "1000"


l4d_infectedbots_spawn_range_min "550"


l4d_infectedbots_spawn_time_max "15"


l4d_infectedbots_spawn_time_min "15"


l4d_infectedbots_spawns_disabled_tank "0"


l4d_infectedbots_spitter_limit "3"


l4d_infectedbots_tank_limit "0"


l4d_infectedbots_tank_spawn_final "0"


l4d_infectedbots_tank_spawn_probability "0"


l4d_infectedbots_versus_coop "0"


l4d_infectedbots_witch_lifespan "200"


l4d_infectedbots_witch_max_limit "0"


l4d_infectedbots_witch_spawn_final "0"


l4d_infectedbots_witch_spawn_time_max "120.0"


l4d_infectedbots_witch_spawn_time_min "90.0"


③进入伺服器后，我使用zlimit指令将特感数量修改至24，同时exec了一个xxx.cfg以修改同种类型特感数，xxx.cfg的内容为
l4d_infectedbots_boomer_limit 4
l4d_infectedbots_smoker_limit 4
l4d_infectedbots_hunter_limit 4
l4d_infectedbots_spitter_limit 4
l4d_infectedbots_jockey_limit 4
l4d_infectedbots_charger_limit 4


④完成以上操作后，大部分情况下，第一波特感的往往刷新只有10多只，如果此时将所有特感处死（ForcePlayerSuicide），下一波的刷新才能够达到24，否则余下每一波的特感刷新总数一直达不到预期的数量

**Comment by fbef0102** [comment]
[版本2.7.5](https://github.com/fbef0102/L4D1_2-Plugins/tree/master/l4dinfectedbots) 發佈
刪除了兩條指令"l4d_infectedbots_spawn_range_max", "l4d_infectedbots_spawn_range_final"
