### ISSUE TITLE
infectedbots

### ISSUE THREAD

**Issue by vikingo12** [fbef0102/L4D1_2-Plugins#24]
L 11/06/2022 - 00:57:48: [SM] Exception reported: Divide by zero
L 11/06/2022 - 00:57:48: [SM] Blaming: optional\l4d_infectedbots.smx
L 11/06/2022 - 00:57:48: [SM] Call stack trace:
L 11/06/2022 - 00:57:48: [SM]   [1] Line 2778, D:\L4D2server\left4dead2\addons\sourcemod\scripting\l4d_infectedbots.sp::Timer_CountSurvivor
L 11/06/2022 - 00:57:48: [SM] Exception reported: Handle 9330066f is invalid (error 1)
L 11/06/2022 - 00:57:48: [SM] Blaming: optional\l4d_infectedbots.smx
L 11/06/2022 - 00:57:48: [SM] Call stack trace:
L 11/06/2022 - 00:57:48: [SM]   [0] CloseHandle
L 11/06/2022 - 00:57:48: [SM]   [1] Line 1608, D:\L4D2server\left4dead2\addons\sourcemod\scripting\l4d_infectedbots.sp::Timer_PluginStart
L 11/06/2022 - 00:57:50: [SM] Exception reported: Handle 9330066f is invalid (error 3)
L 11/06/2022 - 00:57:50: [SM] Blaming: optional\l4d_infectedbots.smx
L 11/06/2022 - 00:57:50: [SM] Call stack trace:
L 11/06/2022 - 00:57:50: [SM]   [0] CloseHandle
L 11/06/2022 - 00:57:50: [SM]   [1] Line 5070, D:\L4D2server\left4dead2\addons\sourcemod\scripting\l4d_infectedbots.sp::ResetTimer
L 11/06/2022 - 00:57:50: [SM]   [2] Line 1762, D:\L4D2server\left4dead2\addons\sourcemod\scripting\l4d_infectedbots.sp::OnMapEnd
L 11/06/2022 - 00:57:51: Error log file session closed.
L 11/06/2022 - 00:58:04: SourceMod error session started
L 11/06/2022 - 00:58:04: Info (map "c3m1_plankcountry") (file "D:\L4D2server\left4dead2\addons\sourcemod\logs\errors_20221106.log")
L 11/06/2022 - 00:58:04: [SM] Exception reported: Handle 9330066f is invalid (error 1)
L 11/06/2022 - 00:58:04: [SM] Blaming: optional\l4d_infectedbots.smx
L 11/06/2022 - 00:58:04: [SM] Call stack trace:
L 11/06/2022 - 00:58:04: [SM]   [0] CloseHandle
L 11/06/2022 - 00:58:04: [SM]   [1] Line 1189, D:\L4D2server\left4dead2\addons\sourcemod\scripting\l4d_infectedbots.sp::ConVarMaxPlayerZombies
L 11/06/2022 - 00:58:05: [SM] Exception reported: Handle 9330066f is invalid (error 1)

**Comment by fbef0102** [comment]
Error line dismatch the current version, please donwload latest version and don't try to modify code
[v2.7.6](https://github.com/fbef0102/L4D1_2-Plugins/tree/master/l4dinfectedbots)

**Comment by acgnmoe** [comment]
對突變坦克血量沒有效果
https://forums.alliedmods.net/showthread.php?t=302140#Commands

**Comment by fbef0102** [comment]
> 對突變坦克血量沒有效果 https://forums.alliedmods.net/showthread.php?t=302140#Commands

因為突變坦克插件有自己的一套Tank血量系統，與這個多特感插件衝突
請關閉多特感插件修改Tank血量的功能，再使用突變坦克插件

```
// If 1, adjust and overrides tank health by this plugin.
l4d_infectedbots_adjust_tankhealth_enable "0"
```
