### ISSUE TITLE
不明原因的multislots无法运行的报错

### ISSUE THREAD

**Issue by Kud-Fountain** [fbef0102/L4D1_2-Plugins#25]
`l4dmultislots.smx ([L4D(2)] MultiSlots Improved): Native "NextBotCreatePlayerBotSurvivorBot" was not found`

尝试使用预编译版本和自行编译均出现该条错误，使用 [Dragokas](https://forums.alliedmods.net/member.php?u=282667) 的 [CreateSurvivorBot.zip](https://forums.alliedmods.net/attachment.php?attachmentid=185769&d=1608745336) 里的测试插件也出现同样的错误。
感谢帮助。

**Comment by fbef0102** [comment]
你有安裝l4d_CreateSurvivorBot.smx嗎
伺服器控制台打上
```php
sm plugins info l4d_CreateSurvivorBot
  Filename: l4d_CreateSurvivorBot.smx
  Title: [L4D1 & L4D2] CreateSurvivorBot (Provides CreateSurvivorBot Native)
  Author: MicroLeo (port by Dragokas)
  Version: 1.0
  URL: https://github.com/dragokas
  Status: running
  Timestamp: 12/24/2020 19:55:39
  Hash: 7b2b08a1f4e948b21a18122f4ea3f898
```

**Comment by Kud-Fountain** [comment]
原来如此，是这个插件而不是那个 带 `L4D2` 和 `TEST` 的 插件。问题解决了，感谢帮助
