### ISSUE TITLE
l4d_afk_commands – spectator stuck in overview camera

### ISSUE THREAD

**Issue by Kerouha** [fbef0102/L4D1_2-Plugins#31]
If you spectate Survivors doing the finale mission, and Survivors fail, camera is forced to this kind of "overview" position (if map has one defined).

![image](https://user-images.githubusercontent.com/119249436/219209275-d44ee1d6-93cb-4260-8f81-0c10a4a78b3b.png)

After restart, camera can't be moved. You have to join Survivor team and play as one of Survivors, then camera goes to normal first person mode. Happens on a server with bots and one real player.

**Comment by fbef0102** [comment]
This is official Valve bug, not related to any of my plugins.
Anyway, install [l4d_fix_deathfall_cam by jensewe](https://github.com/Target5150/MoYu_Server_Stupid_Plugins/tree/master/The%20Last%20Stand/l4d_fix_deathfall_cam) to fix.
