### ISSUE TITLE
[kills] kills counter doesnt show at final rescue left 4dead

### ISSUE THREAD

**Issue by username-98** [fbef0102/L4D1_2-Plugins#32]
kills counter doesnt show at final rescue left 4dead1

**Comment by fbef0102** [comment]
Test in left 4 dead 1 hospital roof leaving
![image](https://user-images.githubusercontent.com/12229810/220237422-fd17604a-a1da-4b37-aed8-c5dae085e8b6.png)

**Comment by username-98** [comment]
i had an old version, i just updated, my bad
