### ISSUE TITLE
[lockdown_system-l4d2] tanks spawns inside saferoom 

### ISSUE THREAD

**Issue by username-98** [fbef0102/L4D1_2-Plugins#33]
tanks demolition are spawning inside the saferoom if all survivor are not looking to the saferoom, when their view is not pointed at the saferoom, the tanks spawns inside it
i already set this 2 convars : 
lockdown_system-l4d2_teleport "1"
lockdown_system-l4d2_type "2"
and  after the saferoom door is openned, the tanks wave is spawning inside the saferoom

**Comment by fbef0102** [comment]
> tanks demolition are spawning inside the saferoom if all survivor are not looking to the saferoom, when their view is not pointed at the saferoom, the tanks spawns inside it

Map nav problem, another official bug.
