### ISSUE TITLE
關於L4DVSAutoSpectateOnAFK插件

### ISSUE THREAD

**Issue by w19872001** [fbef0102/L4D1_2-Plugins#34]
您好大大，為了回報特地申請了帳號
插件在偵測閒置狀態時，不管是在何種狀態(場上不動,旁觀或閒置)
倒數期間只要在聊天欄中輸入文字送出即可解除倒數
這意味著可能會遭惡意玩家利用，佔著位子不玩但又不會被踢
想請問這有辦法改進或解決嗎?感謝您的辛苦工作

**Comment by fbef0102** [comment]
這是我故意的，
輸入文字聊天視為不是閒置狀態

你若希望打字不要解除倒數，
[重新下載插件](https://github.com/fbef0102/L4D1_2-Plugins/tree/master/L4DVSAutoSpectateOnAFK)，並更改指令
```c
// If 1, Reset time when player types words in chatbox.
l4d_specafk_say_reset "0"
```

**Comment by w19872001** [comment]
已重下測試，新增指令後完美解決問題
感謝大大的更新工作~~
