### ISSUE TITLE
有關lockdown_system-l4d2的小問題

### ISSUE THREAD

**Issue by w19872001** [fbef0102/L4D1_2-Plugins#35]
// 為1時, 禁止Bot開門與關門
lockdown_system-l4d2_spam_bot_disable "1"

當上述指令設為1時，BOT除了安全屋的門以外連路上一般的門也都不能開
這樣當有角色死亡一段時間後能通過開門重新復活時會導致BOT救不了他們
因為完全開不了任何門，想問這個問題有辦法解決或修正嗎?感謝大大

**Comment by fbef0102** [comment]
Try this version
[lockdown_system-l4d2_b v5.3](https://github.com/fbef0102/L4D1_2-Plugins/files/11035474/lockdown_system-l4d2_b.zip)
