### ISSUE TITLE
l4dinfectedbots插件无法使用

### ISSUE THREAD

**Issue by 2215918947** [fbef0102/L4D1_2-Plugins#37]
错误提示
L 05/22/2023 - 03:48:30: [SM] Exception reported: CDirector::HasAnySurvivorLeftSafeArea not available (WIN/2/1.130).
L 05/22/2023 - 03:48:30: [SM] Blaming: left4dhooks.smx
L 05/22/2023 - 03:48:30: [SM] Call stack trace:
L 05/22/2023 - 03:48:30: [SM]   [0] ThrowNativeError
L 05/22/2023 - 03:48:30: [SM]   [1] Line 182, l4dd\l4dd_natives.sp::ValidateNatives
L 05/22/2023 - 03:48:30: [SM]   [2] Line 1025, l4dd\l4dd_natives.sp::Native_CDirector_HasAnySurvivorLeftSafeArea
L 05/22/2023 - 03:48:30: [SM]   [4] L4D_HasAnySurvivorLeftSafeArea
L 05/22/2023 - 03:48:30: [SM]   [5] Line 2087, d:\Github\Private-Work\L4D2-���\scripting_1.11\l4dinfectedbots.sp::Timer_PlayerLeftStart
L 05/22/2023 - 03:48:31: [SM] Exception reported: CDirector::HasAnySurvivorLeftSafeArea not available (WIN/2/1.130).
L 05/22/2023 - 03:48:31: [SM] Blaming: left4dhooks.smx
L 05/22/2023 - 03:48:31: [SM] Call stack trace:
L 05/22/2023 - 03:48:31: [SM]   [0] ThrowNativeError
L 05/22/2023 - 03:48:31: [SM]   [1] Line 182, l4dd\l4dd_natives.sp::ValidateNatives
L 05/22/2023 - 03:48:31: [SM]   [2] Line 1025, l4dd\l4dd_natives.sp::Native_CDirector_HasAnySurvivorLeftSafeArea
L 05/22/2023 - 03:48:31: [SM]   [4] L4D_HasAnySurvivorLeftSafeArea
L 05/22/2023 - 03:48:31: [SM]   [5] Line 1447, d:\Github\Private-Work\L4D2-���\scripting_1.11\l4dmultislots.sp::Timer_PlayerLeftStart
L 05/22/2023 - 03:48:31: [SM] Exception reported: CDirector::HasAnySurvivorLeftSafeArea not available (WIN/2/1.130).
L 05/22/2023 - 03:48:31: [SM] Blaming: left4dhooks.smx
L 05/22/2023 - 03:48:31: [SM] Call stack trace:
L 05/22/2023 - 03:48:31: [SM]   [0] ThrowNativeError
L 05/22/2023 - 03:48:31: [SM]   [1] Line 182, l4dd\l4dd_natives.sp::ValidateNatives
L 05/22/2023 - 03:48:31: [SM]   [2] Line 1025, l4dd\l4dd_natives.sp::Native_CDirector_HasAnySurvivorLeftSafeArea
L 05/22/2023 - 03:48:31: [SM]   [4] L4D_HasAnySurvivorLeftSafeArea
L 05/22/2023 - 03:48:31: [SM]   [5] Line 667, d:\Github\Private-Work\L4D2-���\scripting_1.11\l4d_afk_commands.sp::Timer_PlayerLeftStart
L 05/22/2023 - 03:48:31: [SM] Exception reported: CDirector::HasAnySurvivorLeftSafeArea not available (WIN/2/1.130).
L 05/22/2023 - 03:48:31: [SM] Blaming: left4dhooks.smx
L 05/22/2023 - 03:48:31: [SM] Call stack trace:
L 05/22/2023 - 03:48:31: [SM]   [0] ThrowNativeError
L 05/22/2023 - 03:48:31: [SM]   [1] Line 182, l4dd\l4dd_natives.sp::ValidateNatives
L 05/22/2023 - 03:48:31: [SM]   [2] Line 1025, l4dd\l4dd_natives.sp::Native_CDirector_HasAnySurvivorLeftSafeArea
L 05/22/2023 - 03:48:31: [SM]   [4] L4D_HasAnySurvivorLeftSafeArea
L 05/22/2023 - 03:48:31: [SM]   [5] Line 2087, d:\Github\Private-Work\L4D2-���\scripting_1.11\l4dinfectedbots.sp::Timer_PlayerLeftStart
L 05/22/2023 - 03:48:32: [SM] Exception reported: CDirector::HasAnySurvivorLeftSafeArea not available (WIN/2/1.130).
L 05/22/2023 - 03:48:32: [SM] Blaming: left4dhooks.smx
L 05/22/2023 - 03:48:32: [SM] Call stack trace:
L 05/22/2023 - 03:48:32: [SM]   [0] ThrowNativeError
L 05/22/2023 - 03:48:32: [SM]   [1] Line 182, l4dd\l4dd_natives.sp::ValidateNatives
L 05/22/2023 - 03:48:32: [SM]   [2] Line 1025, l4dd\l4dd_natives.sp::Native_CDirector_HasAnySurvivorLeftSafeArea
L 05/22/2023 - 03:48:32: [SM]   [4] L4D_HasAnySurvivorLeftSafeArea
L 05/22/2023 - 03:48:32: [SM]   [5] Line 1447, d:\Github\Private-Work\L4D2-���\scripting_1.11\l4dmultislots.sp::Timer_PlayerLeftStart
L 05/22/2023 - 03:48:32: [SM] Exception reported: CDirector::HasAnySurvivorLeftSafeArea not available (WIN/2/1.130).
L 05/22/2023 - 03:48:32: [SM] Blaming: left4dhooks.smx
L 05/22/2023 - 03:48:32: [SM] Call stack trace:
L 05/22/2023 - 03:48:32: [SM]   [0] ThrowNativeError
L 05/22/2023 - 03:48:32: [SM]   [1] Line 182, l4dd\l4dd_natives.sp::ValidateNatives
L 05/22/2023 - 03:48:32: [SM]   [2] Line 1025, l4dd\l4dd_natives.sp::Native_CDirector_HasAnySurvivorLeftSafeArea
L 05/22/2023 - 03:48:32: [SM]   [4] L4D_HasAnySurvivorLeftSafeArea
L 05/22/2023 - 03:48:32: [SM]   [5] Line 667, d:\Github\Private-Work\L4D2-���\scripting_1.11\l4d_afk_commands.sp::Timer_PlayerLeftStart

**Comment by fbef0102** [comment]
left4dhooks 的gamedata文件需要更新
[請從這裡下載](https://forums.alliedmods.net/showpost.php?p=2804627&postcount=880)

**Comment by 2215918947** [comment]
谢谢 解决了
