### ISSUE TITLE
Explosive cars — Baggage container behaves like a car.

### ISSUE THREAD

**Issue by SefoNotasi** [fbef0102/L4D1_2-Plugins#39]
Containers with luggage (for example on Dead Air) work the same way as the cars. Also burn and explode if you shoot at them. Looks like under the hood in L4D2 these containers and cars are the same thing:
![Explosion cars bug](https://github.com/fbef0102/L4D1_2-Plugins/assets/62970952/3984158b-bee0-4926-9708-9ddc9b95485e)
Any chance this can be fixed please?

**Comment by fbef0102** [comment]
Give a try
[l4d_explosive_cars v2.3](https://github.com/fbef0102/L4D1_2-Plugins/tree/master/l4d_explosive_cars)

**Comment by SefoNotasi** [comment]
> Give a try [l4d_explosive_cars v2.3](https://github.com/fbef0102/L4D1_2-Plugins/tree/master/l4d_explosive_cars)

I checked, it's fixed. Thank you very much.

**Comment by SefoNotasi** [comment]
> Give a try [l4d_explosive_cars v2.3](https://github.com/fbef0102/L4D1_2-Plugins/tree/master/l4d_explosive_cars)

I checked, it's fixed. Thank you very much.
