### ISSUE TITLE
skeet

### ISSUE THREAD

**Issue by OfficialInstructions** [fbef0102/L4D1_2-Plugins#40]
L 06/10/2023 - 02:20:24: [SM] Exception reported: Not enough space on the heap
L 06/10/2023 - 02:20:24: [SM] Blaming: skeet_database.smx
L 06/10/2023 - 02:20:24: [SM] Call stack trace:
L 06/10/2023 - 02:20:24: [SM]   [1] Line 708, d:\Github\Private-Work\L4D2-����\scripting_1.11\skeet_database.sp::PrintTopSkeetersToClient
L 06/10/2023 - 02:20:24: [SM]   [2] Line 177, d:\Github\Private-Work\L4D2-����\scripting_1.11\skeet_database.sp::Command_Top

**Comment by fbef0102** [comment]
Use this
[skeet_database.zip](https://github.com/fbef0102/L4D1_2-Plugins/files/11713125/skeet_database.zip)

**Comment by OfficialInstructions** [comment]
`L 06/12/2023 - 00:55:44: [SM] Exception reported: Ran out of memory to sort
L 06/12/2023 - 00:55:44: [SM] Blaming: [Infected]_Skeet_Database_1.smx
L 06/12/2023 - 00:55:44: [SM] Call stack trace:
L 06/12/2023 - 00:55:44: [SM]   [0] SortCustom2D
L 06/12/2023 - 00:55:44: [SM]   [1] Line 726, c:\Users\stran\Desktop\skeet.sp::PrintTopSkeetersToClient
L 06/12/2023 - 00:55:44: [SM]   [2] Line 177, c:\Users\stran\Desktop\skeet.sp::Command_Top`

**Comment by fbef0102** [comment]
[skeet_database v2.4](https://github.com/fbef0102/L4D1_2-Plugins/files/11716911/skeet_database.zip)
