### ISSUE TITLE
Infected Bots

### ISSUE THREAD

**Issue by Unfellowed** [fbef0102/L4D1_2-Plugins#41]
When the Tank is about to die, the player controls the Tank using the !js, !ji commands repeatedly causing the Tank's health to be reset from scratch.

**Comment by fbef0102** [comment]
Can you record video?

**Comment by Unfellowed** [comment]
I need someone on the Infected side to reproduce the bug, but there isn't one right now. :(
https://youtu.be/IJo6VC-mJwo

**Comment by fbef0102** [comment]
> 

I don't think the full health bug is from Infected Bots plugin,
I test with friends, tank health is still remaining red and when tank player switches team in coop mode.

According to your video, it seems like you have other plugins related to Tanks,
maybe one of your plugin resets tank health when bot takes over control **(view as "Tank Spawn")** in coop mode.
