### ISSUE TITLE
About l4dinfectedbots plugins error

### ISSUE THREAD

**Issue by cy115** [fbef0102/L4D1_2-Plugins#44]
sorry for my poor English
eeverytime I play L4d2 on my server using your multi_infectedbots plugin, however it can work with less than 5 players, as long as the num of players add to 5 or more, the server begins to kicked my mates,just output like this: kicked by console: CbaseEntity::InputKill().

another question is whenever it start the server and were in using, sourcemod logs file will pretend the message like this:

L 07/21/2023 - 02:58:08: [SM] Exception reported: Divide by zero
L 07/21/2023 - 02:58:08: [SM] Blaming: l4dinfectedbots.smx
L 07/21/2023 - 02:58:08: [SM] Call stack trace:
L 07/21/2023 - 02:58:08: [SM]   [1] Line 2201, C:\Users\cy115\Desktop\scripting\l4dinfectedbots.sp::Timer_CountSurvivor
L 07/21/2023 - 02:58:20: [SM] Exception reported: Handle a780066b is invalid (error 1)
L 07/21/2023 - 02:58:20: [SM] Blaming: l4dinfectedbots.smx
L 07/21/2023 - 02:58:20: [SM] Call stack trace:
L 07/21/2023 - 02:58:20: [SM]   [0] CloseHandle
L 07/21/2023 - 02:58:20: [SM]   [1] Line 1804, C:\Users\cy115\Desktop\scripting\l4dinfectedbots.sp::evtPlayerSpawn
L 07/21/2023 - 02:58:20: [SM] Exception reported: Handle a780066b is invalid (error 1)
L 07/21/2023 - 02:58:20: [SM] Blaming: l4dinfectedbots.smx
L 07/21/2023 - 02:58:20: [SM] Call stack trace:
L 07/21/2023 - 02:58:20: [SM]   [0] CloseHandle
L 07/21/2023 - 02:58:20: [SM]   [1] Line 1804, C:\Users\cy115\Desktop\scripting\l4dinfectedbots.sp::evtPlayerSpawn
L 07/21/2023 - 02:58:20: [SM] Exception reported: Handle a780066b is invalid (error 1)
L 07/21/2023 - 02:58:20: [SM] Blaming: l4dinfectedbots.smx
L 07/21/2023 - 02:58:20: [SM] Call stack trace:
L 07/21/2023 - 02:58:20: [SM]   [0] CloseHandle
L 07/21/2023 - 02:58:20: [SM]   [1] Line 1804, C:\Users\cy115\Desktop\scripting\l4dinfectedbots.sp::evtPlayerSpawn
L 07/21/2023 - 02:58:20: [SM] Exception reported: Handle a780066b is invalid (error 1)
L 07/21/2023 - 02:58:20: [SM] Blaming: l4dinfectedbots.smx
L 07/21/2023 - 02:58:20: [SM] Call stack trace:
L 07/21/2023 - 02:58:20: [SM]   [0] CloseHandle
L 07/21/2023 - 02:58:20: [SM]   [1] Line 1804, C:\Users\cy115\Desktop\scripting\l4dinfectedbots.sp::evtPlayerSpawn
L 07/21/2023 - 02:58:20: [SM] Exception reported: Handle a780066b is invalid (error 1)
L 07/21/2023 - 02:58:20: [SM] Blaming: l4dinfectedbots.smx
L 07/21/2023 - 02:58:20: [SM] Call stack trace:
L 07/21/2023 - 02:58:20: [SM]   [0] CloseHandle
L 07/21/2023 - 02:58:20: [SM]   [1] Line 2064, C:\Users\cy115\Desktop\scripting\l4dinfectedbots.sp::PlayerChangeTeamCheck
L 07/21/2023 - 02:59:38: [SM] Exception reported: Handle a780066b is invalid (error 1)
L 07/21/2023 - 02:59:38: [SM] Blaming: l4dinfectedbots.smx
L 07/21/2023 - 02:59:38: [SM] Call stack trace:
L 07/21/2023 - 02:59:38: [SM]   [0] CloseHandle
L 07/21/2023 - 02:59:38: [SM]   [1] Line 1918, C:\Users\cy115\Desktop\scripting\l4dinfectedbots.sp::evtPlayerDeath
L 07/21/2023 - 02:59:38: [SM] Exception reported: Handle a780066b is invalid (error 3)
L 07/21/2023 - 02:59:38: [SM] Blaming: l4dinfectedbots.smx
L 07/21/2023 - 02:59:38: [SM] Call stack trace:
L 07/21/2023 - 02:59:38: [SM]   [0] CloseHandle
L 07/21/2023 - 02:59:38: [SM]   [1] Line 4609, C:\Users\cy115\Desktop\scripting\l4dinfectedbots.sp::ResetTimer
L 07/21/2023 - 02:59:38: [SM]   [2] Line 1136, C:\Users\cy115\Desktop\scripting\l4dinfectedbots.sp::evtRoundEnd
L 07/21/2023 - 02:59:46: [SM] Exception reported: Handle a780066b is invalid (error 3)
L 07/21/2023 - 02:59:46: [SM] Blaming: l4dinfectedbots.smx
L 07/21/2023 - 02:59:46: [SM] Call stack trace:
L 07/21/2023 - 02:59:46: [SM]   [0] CloseHandle
L 07/21/2023 - 02:59:46: [SM]   [1] Line 1804, C:\Users\cy115\Desktop\scripting\l4dinfectedbots.sp::evtPlayerSpawn
L 07/21/2023 - 02:59:46: [SM] Exception reported: Handle a780066b is invalid (error 3)
L 07/21/2023 - 02:59:46: [SM] Blaming: l4dinfectedbots.smx
L 07/21/2023 - 02:59:46: [SM] Call stack trace:
L 07/21/2023 - 02:59:46: [SM]   [0] CloseHandle
L 07/21/2023 - 02:59:46: [SM]   [1] Line 1804, C:\Users\cy115\Desktop\scripting\l4dinfectedbots.sp::evtPlayerSpawn
L 07/21/2023 - 02:59:46: [SM] Exception reported: Handle a780066b is invalid (error 3)
L 07/21/2023 - 02:59:46: [SM] Blaming: l4dinfectedbots.smx
L 07/21/2023 - 02:59:46: [SM] Call stack trace:
L 07/21/2023 - 02:59:46: [SM]   [0] CloseHandle
L 07/21/2023 - 02:59:46: [SM]   [1] Line 1804, C:\Users\cy115\Desktop\scripting\l4dinfectedbots.sp::evtPlayerSpawn
L 07/21/2023 - 02:59:46: [SM] Exception reported: Handle a780066b is invalid (error 3)
L 07/21/2023 - 02:59:46: [SM] Blaming: l4dinfectedbots.smx
L 07/21/2023 - 02:59:46: [SM] Call stack trace:
L 07/21/2023 - 02:59:46: [SM]   [0] CloseHandle
L 07/21/2023 - 02:59:46: [SM]   [1] Line 1804, C:\Users\cy115\Desktop\scripting\l4dinfectedbots.sp::evtPlayerSpawn
L 07/21/2023 - 02:59:46: [SM] Exception reported: Handle a780066b is invalid (error 3)
L 07/21/2023 - 02:59:46: [SM] Blaming: l4dinfectedbots.smx
L 07/21/2023 - 02:59:46: [SM] Call stack trace:
L 07/21/2023 - 02:59:46: [SM]   [0] CloseHandle
L 07/21/2023 - 02:59:46: [SM]   [1] Line 1009, C:\Users\cy115\Desktop\scripting\l4dinfectedbots.sp::Timer_PluginStart
L 07/21/2023 - 03:00:07: [SM] Exception reported: Using two team colors in one message is not allowed
L 07/21/2023 - 03:00:07: [SM] Blaming: l4d2_create_panic.smx
L 07/21/2023 - 03:00:07: [SM] Call stack trace:
L 07/21/2023 - 03:00:07: [SM]   [0] ThrowError
L 07/21/2023 - 03:00:07: [SM]   [1] Line 502, colors::CFormat
L 07/21/2023 - 03:00:07: [SM]   [2] Line 142, colors::CPrintToChat
L 07/21/2023 - 03:00:07: [SM]   [3] Line 249, colors::CPrintToChatAll
L 07/21/2023 - 03:00:07: [SM]   [4] Line 44, C:\Users\cy115\Desktop\scripting\l4d2_create_panic.sp::IsCheckAlarm
L 07/21/2023 - 03:00:27: [SM] Exception reported: Using two team colors in one message is not allowed
L 07/21/2023 - 03:00:27: [SM] Blaming: l4d2_create_panic.smx
L 07/21/2023 - 03:00:27: [SM] Call stack trace:
L 07/21/2023 - 03:00:27: [SM]   [0] ThrowError
L 07/21/2023 - 03:00:27: [SM]   [1] Line 502, colors::CFormat
L 07/21/2023 - 03:00:27: [SM]   [2] Line 142, colors::CPrintToChat
L 07/21/2023 - 03:00:27: [SM]   [3] Line 249, colors::CPrintToChatAll
L 07/21/2023 - 03:00:27: [SM]   [4] Line 44, C:\Users\cy115\Desktop\scripting\l4d2_create_panic.sp::IsCheckAlarm
L 07/21/2023 - 03:00:48: [SM] Exception reported: Handle a780066b is invalid (error 3)
L 07/21/2023 - 03:00:48: [SM] Blaming: l4dinfectedbots.smx
L 07/21/2023 - 03:00:48: [SM] Call stack trace:
L 07/21/2023 - 03:00:48: [SM]   [0] CloseHandle
L 07/21/2023 - 03:00:48: [SM]   [1] Line 2282, C:\Users\cy115\Desktop\scripting\l4dinfectedbots.sp::OnClientDisconnect
L 07/21/2023 - 03:00:48: [SM] Exception reported: Handle a780066b is invalid (error 3)
L 07/21/2023 - 03:00:48: [SM] Blaming: l4dinfectedbots.smx
L 07/21/2023 - 03:00:48: [SM] Call stack trace:
L 07/21/2023 - 03:00:48: [SM]   [0] CloseHandle
L 07/21/2023 - 03:00:48: [SM]   [1] Line 2282, C:\Users\cy115\Desktop\scripting\l4dinfectedbots.sp::OnClientDisconnect
L 07/21/2023 - 03:00:48: [SM] Exception reported: Handle a780066b is invalid (error 3)
L 07/21/2023 - 03:00:48: [SM] Blaming: l4dinfectedbots.smx
L 07/21/2023 - 03:00:48: [SM] Call stack trace:
L 07/21/2023 - 03:00:48: [SM]   [0] CloseHandle
L 07/21/2023 - 03:00:48: [SM]   [1] Line 2282, C:\Users\cy115\Desktop\scripting\l4dinfectedbots.sp::OnClientDisconnect
L 07/21/2023 - 03:00:48: [SM] Exception reported: Handle a780066b is invalid (error 3)
L 07/21/2023 - 03:00:48: [SM] Blaming: l4dinfectedbots.smx
L 07/21/2023 - 03:00:48: [SM] Call stack trace:
L 07/21/2023 - 03:00:48: [SM]   [0] CloseHandle
L 07/21/2023 - 03:00:48: [SM]   [1] Line 2282, C:\Users\cy115\Desktop\scripting\l4dinfectedbots.sp::OnClientDisconnect
L 07/21/2023 - 03:00:48: [SM] Exception reported: Handle a780066b is invalid (error 3)
L 07/21/2023 - 03:00:48: [SM] Blaming: l4dinfectedbots.smx
L 07/21/2023 - 03:00:48: [SM] Call stack trace:
L 07/21/2023 - 03:00:48: [SM]   [0] CloseHandle
L 07/21/2023 - 03:00:48: [SM]   [1] Line 4609, C:\Users\cy115\Desktop\scripting\l4dinfectedbots.sp::ResetTimer
L 07/21/2023 - 03:00:48: [SM]   [2] Line 1170, C:\Users\cy115\Desktop\scripting\l4dinfectedbots.sp::OnMapEnd
L 07/21/2023 - 03:00:48: Error log file session closed.
L 07/21/2023 - 03:01:04: SourceMod error session started
L 07/21/2023 - 03:01:04: Info (map "c2m1_highway") (file "/root/Steam/steamapps/common/Left 4 Dead 2 Dedicated Server/left4dead2/addons/sourcemod/logs/errors_20230721.log")
L 07/21/2023 - 03:01:04: [SM] Exception reported: Handle a780066b is invalid (error 3)
L 07/21/2023 - 03:01:04: [SM] Blaming: l4dinfectedbots.smx
L 07/21/2023 - 03:01:04: [SM] Call stack trace:
L 07/21/2023 - 03:01:04: [SM]   [0] CloseHandle
L 07/21/2023 - 03:01:04: [SM]   [1] Line 1804, C:\Users\cy115\Desktop\scripting\l4dinfectedbots.sp::evtPlayerSpawn
L 07/21/2023 - 03:01:04: [SM] Exception reported: Handle a780066b is invalid (error 3)
L 07/21/2023 - 03:01:04: [SM] Blaming: l4dinfectedbots.smx
L 07/21/2023 - 03:01:04: [SM] Call stack trace:
L 07/21/2023 - 03:01:04: [SM]   [0] CloseHandle
L 07/21/2023 - 03:01:04: [SM]   [1] Line 1804, C:\Users\cy115\Desktop\scripting\l4dinfectedbots.sp::evtPlayerSpawn
L 07/21/2023 - 03:01:04: [SM] Exception reported: Handle a780066b is invalid (error 3)
L 07/21/2023 - 03:01:04: [SM] Blaming: l4dinfectedbots.smx
L 07/21/2023 - 03:01:04: [SM] Call stack trace:
L 07/21/2023 - 03:01:04: [SM]   [0] CloseHandle
L 07/21/2023 - 03:01:04: [SM]   [1] Line 1804, C:\Users\cy115\Desktop\scripting\l4dinfectedbots.sp::evtPlayerSpawn
L 07/21/2023 - 03:01:04: [SM] Exception reported: Handle a780066b is invalid (error 3)
L 07/21/2023 - 03:01:04: [SM] Blaming: l4dinfectedbots.smx
L 07/21/2023 - 03:01:04: [SM] Call stack trace:
L 07/21/2023 - 03:01:04: [SM]   [0] CloseHandle
L 07/21/2023 - 03:01:04: [SM]   [1] Line 1804, C:\Users\cy115\Desktop\scripting\l4dinfectedbots.sp::evtPlayerSpawn
L 07/21/2023 - 03:01:05: [SM] Exception reported: Handle a780066b is invalid (error 3)
L 07/21/2023 - 03:01:05: [SM] Blaming: l4dinfectedbots.smx
L 07/21/2023 - 03:01:05: [SM] Call stack trace:
L 07/21/2023 - 03:01:05: [SM]   [0] CloseHandle
L 07/21/2023 - 03:01:05: [SM]   [1] Line 1009, C:\Users\cy115\Desktop\scripting\l4dinfectedbots.sp::Timer_PluginStart
L 07/21/2023 - 03:01:05: [SM] Exception reported: Handle a780066b is invalid (error 3)
L 07/21/2023 - 03:01:05: [SM] Blaming: l4dinfectedbots.smx
L 07/21/2023 - 03:01:05: [SM] Call stack trace:
L 07/21/2023 - 03:01:05: [SM]   [0] CloseHandle
L 07/21/2023 - 03:01:05: [SM]   [1] Line 2064, C:\Users\cy115\Desktop\scripting\l4dinfectedbots.sp::PlayerChangeTeamCheck
L 07/21/2023 - 03:01:19: [SM] Exception reported: Using two team colors in one message is not allowed
L 07/21/2023 - 03:01:19: [SM] Blaming: l4d2_create_panic.smx
L 07/21/2023 - 03:01:19: [SM] Call stack trace:
L 07/21/2023 - 03:01:19: [SM]   [0] ThrowError
L 07/21/2023 - 03:01:19: [SM]   [1] Line 502, colors::CFormat
L 07/21/2023 - 03:01:19: [SM]   [2] Line 142, colors::CPrintToChat
L 07/21/2023 - 03:01:19: [SM]   [3] Line 249, colors::CPrintToChatAll
L 07/21/2023 - 03:01:19: [SM]   [4] Line 44, C:\Users\cy115\Desktop\scripting\l4d2_create_panic.sp::IsCheckAlarm
L 07/21/2023 - 03:01:34: [SM] Exception reported: Handle a780066b is invalid (error 3)
L 07/21/2023 - 03:01:34: [SM] Blaming: l4dinfectedbots.smx
L 07/21/2023 - 03:01:34: [SM] Call stack trace:
L 07/21/2023 - 03:01:34: [SM]   [0] CloseHandle
L 07/21/2023 - 03:01:34: [SM]   [1] Line 2282, C:\Users\cy115\Desktop\scripting\l4dinfectedbots.sp::OnClientDisconnect
L 07/21/2023 - 03:01:34: [SM] Exception reported: Handle a780066b is invalid (error 3)
L 07/21/2023 - 03:01:34: [SM] Blaming: l4dinfectedbots.smx
L 07/21/2023 - 03:01:34: [SM] Call stack trace:
L 07/21/2023 - 03:01:34: [SM]   [0] CloseHandle
L 07/21/2023 - 03:01:34: [SM]   [1] Line 1804, C:\Users\cy115\Desktop\scripting\l4dinfectedbots.sp::evtPlayerSpawn
L 07/21/2023 - 03:01:34: [SM] Exception reported: Handle a780066b is invalid (error 3)
L 07/21/2023 - 03:01:34: [SM] Blaming: l4dinfectedbots.smx
L 07/21/2023 - 03:01:34: [SM] Call stack trace:
L 07/21/2023 - 03:01:34: [SM]   [0] CloseHandle
L 07/21/2023 - 03:01:34: [SM]   [1] Line 2282, C:\Users\cy115\Desktop\scripting\l4dinfectedbots.sp::OnClientDisconnect
L 07/21/2023 - 03:01:34: [SM] Exception reported: Handle a780066b is invalid (error 3)
L 07/21/2023 - 03:01:34: [SM] Blaming: l4dinfectedbots.smx
L 07/21/2023 - 03:01:34: [SM] Call stack trace:
L 07/21/2023 - 03:01:34: [SM]   [0] CloseHandle
L 07/21/2023 - 03:01:34: [SM]   [1] Line 2282, C:\Users\cy115\Desktop\scripting\l4dinfectedbots.sp::OnClientDisconnect
L 07/21/2023 - 03:01:34: [SM] Exception reported: Handle a780066b is invalid (error 3)
L 07/21/2023 - 03:01:34: [SM] Blaming: l4dinfectedbots.smx
L 07/21/2023 - 03:01:34: [SM] Call stack trace:
L 07/21/2023 - 03:01:34: [SM]   [0] CloseHandle
L 07/21/2023 - 03:01:34: [SM]   [1] Line 2282, C:\Users\cy115\Desktop\scripting\l4dinfectedbots.sp::OnClientDisconnect
L 07/21/2023 - 03:01:34: [SM] Exception reported: Handle a780066b is invalid (error 1)
L 07/21/2023 - 03:01:34: [SM] Blaming: l4dinfectedbots.smx
L 07/21/2023 - 03:01:34: [SM] Call stack trace:
L 07/21/2023 - 03:01:34: [SM]   [0] CloseHandle
L 07/21/2023 - 03:01:34: [SM]   [1] Line 2282, C:\Users\cy115\Desktop\scripting\l4dinfectedbots.sp::OnClientDisconnect
L 07/21/2023 - 03:01:34: [SM] Exception reported: Handle a780066b is invalid (error 1)
L 07/21/2023 - 03:01:34: [SM] Blaming: l4dinfectedbots.smx
L 07/21/2023 - 03:01:34: [SM] Call stack trace:
L 07/21/2023 - 03:01:34: [SM]   [0] CloseHandle
L 07/21/2023 - 03:01:34: [SM]   [1] Line 4609, C:\Users\cy115\Desktop\scripting\l4dinfectedbots.sp::ResetTimer
L 07/21/2023 - 03:01:34: [SM]   [2] Line 1136, C:\Users\cy115\Desktop\scripting\l4dinfectedbots.sp::evtRoundEnd

**Comment by fbef0102** [comment]
> the server begins to kicked my mates,just output like this: kicked by console: CbaseEntity::InputKill().
What is mate?

> L 07/21/2023 - 02:58:08: [SM] Exception reported: Divide by zero
> L 07/21/2023 - 02:58:08: [SM] Blaming: l4dinfectedbots.smx
> L 07/21/2023 - 02:58:08: [SM] Call stack trace:
> L 07/21/2023 - 02:58:08: [SM] [1] Line 2201, C:\Users\cy115\Desktop\scripting\l4dinfectedbots.sp::Timer_CountSurvivor
> L 07/21/2023 - 02:58:20: [SM] Exception reported: Handle a780066b is invalid (error 1)
> ...

Your error lines does not match latest version, please download and update [latest version](https://github.com/fbef0102/L4D1_2-Plugins/tree/master/l4dinfectedbots)

**Comment by cy115** [comment]
> > the server begins to kicked my mates,just output like this: kicked by console: CbaseEntity::InputKill().
> 
> What is mate?
> 
> > L 07/21/2023 - 02:58:08: [SM] Exception reported: Divide by zero
> > L 07/21/2023 - 02:58:08: [SM] Blaming: l4dinfectedbots.smx
> > L 07/21/2023 - 02:58:08: [SM] Call stack trace:
> > L 07/21/2023 - 02:58:08: [SM] [1] Line 2201, C:\Users\cy115\Desktop\scripting\l4dinfectedbots.sp::Timer_CountSurvivor
> > L 07/21/2023 - 02:58:20: [SM] Exception reported: Handle a780066b is invalid (error 1)
> > ...
> 
> Your error lines does not match latest version, please download and update [latest version](https://github.com/fbef0102/L4D1_2-Plugins/tree/master/l4dinfectedbots)

i will soon give you the newest repyl, forgive i used "mate" to replace my guys play together

**Comment by cy115** [comment]
thanks for your help, now it works correcttly, however.   :)
if something error occure i will tell you
