### ISSUE TITLE
gamemode-based_configs的疑问

### ISSUE THREAD

**Issue by Majestymo** [fbef0102/L4D1_2-Plugins#49]
你好harry，https://github.com/fbef0102/L4D1_2-Plugins/tree/master/gamemode-based_configs
这个插件貌似会在更换模式后一直循环执行对应模式的cfg导致无法更换模式、卡服等问题，我用的是Silvers 的更换模式插件https://forums.alliedmods.net/showthread.php?p=1658942
在server.cfg里面加载了gamemode-based_configs这个插件，进服之后会直接卡服，如果对应模式的cfg里面有卸载、加载插件的话

**Comment by fbef0102** [comment]
把你的server.cfg以及gamemode-based_configs的cfg貼上來

**Comment by Majestymo** [comment]
[file.zip](https://github.com/fbef0102/L4D1_2-Plugins/files/13713307/file.zip)

**Comment by fbef0102** [comment]
首先你的寫法很奇怪
server.cfg是每次地圖載入時(切換關卡)都會執行的文件
不懂每次地圖開始時載入gamemode-based_configs.smx用意是甚麼
```c
sm plugins load optional/gamemode-based_configs.smx
```

再來是不應該在tankrun.cfg寫插件卸載或插件載入
這個插件只適合寫指令，因為執行tankrun.cfg的時間點為
1. 每次地圖載入時(切換關卡)
2. 遊戲模式/突變模式改變時
伺服器每次地圖載入後都會執行tankrun.cfg，所以你的服才陷入死循還

我猜你應該是安裝藥抗那種插件配置?
最好的方式是，
1.更換模式時才卸載或載入插件
2.tankrun.cfg只留下指令，不要寫```sm plugins load, sm exts load, sm plugins unload....```

**Comment by Majestymo** [comment]
我的想法是，在更换配置模式后自动配置该模式对应的插件和配置，也用过confogl插件，但是这个插件他的item——track部分会导致安全室内的急救包消失，所以想尝试下其他的插件，按理来说，sm plugins load等sm平台的指令，在安装了sm平台之后也就是相当于配置的指令了，另外加载改插件写在server里面是为了方便演示，因为sm平台加载完插件之后，只要路径一致，是不会重复加载该插件的，所以这个插件不能实现插件的卸载和加载，只能更改对应的cvar值吗

**Comment by fbef0102** [comment]
> 所以这个插件不能实现插件的卸载和加载，只能更改对应的cvar值吗
是的

你可以試試看刪除指令
看看是哪個影響了卡服 死循環
server.cfg
```c
sm plugins load optional/gamemode-based_configs.smx
```
tankrun.cfg
```c
sm_cvar mp_gamemode "tankrun" 
``

**Comment by Majestymo** [comment]
![{9E914B03-737A-4f6f-98E4-E927E2E2CC76}](https://github.com/fbef0102/L4D1_2-Plugins/assets/57446724/a7c7ec7b-8ba0-441c-acf7-090f5f04921f)
删除这个指令后服务器加载正常
#shell
sm plugins load optional/gamemode-based_configs.smx
删除这个指令，依旧加载插件时服务器卡服不断出现此现象
#shell
sm_cvar mp_gamemode "tankrun" 
``
![issue](https://github.com/fbef0102/L4D1_2-Plugins/assets/57446724/b14dc373-5874-4b30-8d0c-499f710d47f3)

**Comment by fbef0102** [comment]
因為
執行tankrun.cfg卸載所有插件 (sm plugins unload_all)
->然後server.cfg加載gamemode-based_configs.smx (sm plugins load optional/gamemode-based_configs.smx)
->gamemode-based_configs.smx 被加載時會執行tankrun.cfg
結果就死循環

**Comment by Majestymo** [comment]
哦哦，原来是这样QAQ

**Comment by Majestymo** [comment]
谢谢哈利答疑解惑
