### ISSUE TITLE
cvar disable plugin?

### ISSUE THREAD

**Issue by Benjamin38M** [fbef0102/L4D1_2-Plugins#5]
is there any cvar to disable the plugin?

**Comment by fbef0102** [comment]
which plugin you talking about?

**Comment by Benjamin38M** [comment]
l4dinfectedbots

**Comment by fbef0102** [comment]
No

**Comment by Benjamin38M** [comment]
Ok, thanks for answering

**Comment by fbef0102** [comment]
download [Infected Bots Control Impoved](https://github.com/fbef0102/L4D1_2-Plugins/tree/master/l4dinfectedbots) **Version 2.6.2 or above**
- Only remove witches that are spawned by this plugin, make sure this plugin won't affect director witch or any other plugin that could spawn witch.
- Compatibility support for SourceMod 1.11. Fixed various warnings.
- Add convars to turn off this plugin.
```c
// 0=Plugin off, 1=Plugin on.
l4d_infectedbots_allow "1"

// Turn on the plugin in these game modes, separate by commas (no spaces). (Empty = all).
l4d_infectedbots_modes ""

// Turn off the plugin in these game modes, separate by commas (no spaces). (Empty = none).
l4d_infectedbots_modes_off ""

// Turn on the plugin in these game modes. 0=All, 1=Coop/Realism, 2=Survival, 4=Versus, 8=Scavenge. Add numbers together.
l4d_infectedbots_modes_tog "5"
```
