### ISSUE TITLE
cannounce: Not working on listen server, no connect sound, database download

### ISSUE THREAD

**Issue by deprid** [fbef0102/L4D1_2-Plugins#55]
I know the description says 'Dedicated Server Only'. Is there any way to force it to work on listen server by something like installing Left 4 Dead 2 Dedicated Server and port forward the router IP?

There's no connect sound after player joining when I tried this.

You don't need to take extra steps of registering on maxmind.com to download the country and city database. Just download latest version here: https://github.com/wp-statistics/GeoLite2-Country and https://github.com/wp-statistics/GeoLite2-City

**Comment by fbef0102** [comment]
> I know the description says 'Dedicated Server Only'. Is there any way to force it to work on listen server by something like installing Left 4 Dead 2 Dedicated Server and port forward the router IP?
As far as I know, there is no way.


> There's no connect sound after player joining when I tried this.
> 
> You don't need to take extra steps of registering on maxmind.com to download the country and city database. Just download latest version here: https://github.com/wp-statistics/GeoLite2-Country and https://github.com/wp-statistics/GeoLite2-City

Thank you, good thing to know that
