### ISSUE TITLE
Infected Bots生成特感会中断

### ISSUE THREAD

**Issue by 1164715233** [fbef0102/L4D1_2-Plugins#56]
请问下当在一个小区域内活动时，例如和克在一个房间战斗，（没设置克局停刷）有走廊视野看不到的地方也不会刷特，或者在一辆军车上溜克，在一个房间内防守，特感都会停止刷新，这种情况，只有往前走动了，特感才会刷新出来，这是什么原因造成的?

**Comment by 1164715233** [comment]
貌似走过的地方就不会刷特了

**Comment by fbef0102** [comment]
> 请问下当在一个小区域内活动时，例如和克在一个房间战斗，（没设置克局停刷）有走廊视野看不到的地方也不会刷特，或者在一辆军车上溜克，在一个房间内防守，特感都会停止刷新，这种情况，只有往前走动了，特感才会刷新出来，这是什么原因造成的?

你幫自己解答了，此遊戲的生成機制
> 貌似走过的地方就不会刷特了
