### ISSUE TITLE
5+ player plugins and Steam Validation Rejected issue

### ISSUE THREAD

**Issue by deprid** [fbef0102/L4D1_2-Plugins#57]
**Issue 1:** Server enforcing lerp and disabling texture mod on client
I tried out the tutorial by installing all the prepared and required plugins plus deathcheck (Harry Version) and AFK and Join Team Commands Improved Version. But one of my client got issue with the server disabling his texture mod (a low-poly package) and the server enforcing lerp to 100. We both played last night just fine (before installing all those 5+ player plugins). So today, he left the server because he said "the game glitch more if I don't have a performance enhance mod". He also said it was not a consistency error.

**Issue 2:** S3: Duplicate client connection: UserID: 3 SteamID 1100001071959f0 RejectConnection: x.x.x.x:27005 - STEAM validation rejected
Also I got other issue with L4D2-Server4Dead (SteamCMD), most of the time I got 'Disconnected Steam Validation Rejected' using the mm_dedicated_force_servers before creating lobby (best available dedicated). Sometimes I can join my server by firstly joining the server (in the Steam Group Browser at the bottom of menu), exit, and then do the mm_dedicated trick. 

And I always got the Steam Validation Rejected whenever I try to join the server via Lobby > Steam Group server

Do you have idea how to fix those issues?

**Comment by fbef0102** [comment]
> **Issue 1:** Server enforcing lerp and disabling texture mod on client I tried out the tutorial by installing all the prepared and required plugins plus deathcheck (Harry Version) and AFK and Join Team Commands Improved Version. But one of my client got issue with the server disabling his texture mod (a low-poly package) and the server enforcing lerp to 100. We both played last night just fine (before installing all those 5+ player plugins). So today, he left the server because he said "the game glitch more if I don't have a performance enhance mod". He also said it was not a consistency error.

None of my plugins would lock client lerp or force to disable client mod. 
Players can still enable mod and change their lerp even you install sourcemod and 5+ players plugin, you should check plugin list

> **Issue 2:** S3: Duplicate client connection: UserID: 3 SteamID 1100001071959f0 RejectConnection: x.x.x.x:27005 - STEAM validation rejected Also I got other issue with L4D2-Server4Dead (SteamCMD), most of the time I got 'Disconnected Steam Validation Rejected' using the mm_dedicated_force_servers before creating lobby (best available dedicated). Sometimes I can join my server by firstly joining the server (in the Steam Group Browser at the bottom of menu), exit, and then do the mm_dedicated trick.
> 
> And I always got the Steam Validation Rejected whenever I try to join the server via Lobby > Steam Group server
> 
> Do you have idea how to fix those issues?

1. Don't expose IP on the internet, or ddos attack will come to you
2. Not only you have this problem, lots of people have  "Steam Validation Rejected" bug since this year, I think valve probably mess up in recent l4d2 update. I can't help anything here, you can report to steam support.

**Comment by fbef0102** [comment]
If you have [left4dhooks](https://forums.alliedmods.net/showthread.php?t=321696), check cfg/sourcemod/left4dhooks.cfg

```c
// Addons Manager (-1: use addonconfig; 0: disable addons; 1: enable addons.)
// -
// Default: "-1"
l4d2_addons_eclipse "1"
```

**Comment by deprid** [comment]
Issue 1: Server disables client's addon
Settings l4d2_addons_eclipse from default to "1" works! I believe the reason my friend couldn't use his addon was because we're playing using 8 player lobby addon. So the game detected it as versus mode, using default "-1" disable addon in versus. By forcing enable addon "1", my friend can join my 8 player mod game with his addons enabled.

Issue 2: Steam Validation Rejected 
I kinda found the workaround myself. It's because I set sv_steamgroup_exclusive "1" so that I must first join the server via Steam group browser before using mm_dedicated_force_servers <IP> and creating lobby. The step: Open game > Open server > Direct join and exit > mm_dedicated_force_servers <IP> > Create lobby and start the game
