### ISSUE TITLE
bequiet doesn't hide console cvar changes

### ISSUE THREAD

**Issue by vikingo12** [fbef0102/L4D1_2-Plugins#6]

**Comment by fbef0102** [comment]
hide cvar changes announcement in chatbox, not hide in server console
<img src="https://i.imgur.com/yBOLTvN.png" alt="yBOLTvN.png" width="1100" height = "550">

**Comment by vikingo12** [comment]
![20210218204758_1](https://user-images.githubusercontent.com/75884589/108374008-4eb6f600-7222-11eb-99f9-024b85dc10ba.jpg)
doesn't hide from chatbox?

**Comment by fbef0102** [comment]
I think You misunderstand, those messages in your picture are from sourcemod plugin called **"basecommands.smx"** (one part of sourcemod), they are NOT generated by server.
Look at the prefix, it has "**[SM]**"
see https://github.com/alliedmodders/sourcemod/blob/617fb77ea02076cc70be84c6092ebcfc81d54cc2/plugins/basecommands.sp#L322-L331
and here
https://github.com/alliedmodders/sourcemod/blob/617fb77ea02076cc70be84c6092ebcfc81d54cc2/plugins/basecommands.sp#L368-L377
The basecommands.smx prints these message, not server

Generally speaking, bequiet.smx only blocks red messages, can't block the yellow (see picture below)
<img src="https://i.imgur.com/LujUks0.png" alt="FGkLDMp.png" width="1100" height = "550">

**Comment by vikingo12** [comment]
okk thanks
