### ISSUE TITLE
l4dinfectedbots问题

### ISSUE THREAD

**Issue by 2215918947** [fbef0102/L4D1_2-Plugins#62]
修改l4dinfectedbots\data\l4dinfectedbots里面的coop文件任何数值，启动游戏之后插件就无效了，不修改任何数值就可以正常运行，无错误代码。。

**Comment by fbef0102** [comment]
上傳你修改後的coop.cfg

**Comment by 2215918947** [comment]
"1"
    {
        "smoker_limit"      "0"
        "boomer_limit"      "1"
        "hunter_limit"      "1"
        "spitter_limit"     "1"
        "jockey_limit"      "1"
        "charger_limit"     "1"
        "max_specials"      "1"

        "spawn_time_max"        "60.0"
        "spawn_time_min"        "50.0"

        "tank_limit"                "0"
        "tank_health"               "0"

        "witch_max_limit"           "2"
        "witch_spawn_time_max"      "200.0"
        "witch_spawn_time_min"      "200.0"

        "common_limit"              "-1"
    }

    // When there are only 2 alive survivors in server
    // 當伺服器只有兩名活著倖存者時，讀取以下設置
    "2"
    {
        "smoker_limit"      "1"
        "boomer_limit"      "1"
        "hunter_limit"      "2"
        "spitter_limit"     "1"
        "jockey_limit"      "1"
        "charger_limit"     "1"
        "max_specials"      "2"

        "spawn_time_max"        "60.0"
        "spawn_time_min"        "50.0"

        "tank_limit"          "0"
        "tank_health"         "0"

        "witch_max_limit"           "1"
        "witch_spawn_time_max"      "180.0"
        "witch_spawn_time_min"      "180.0"

        "common_limit"        "-1"
    }

    // When there are only 3 alive survivors in server
    // 當伺服器只有三名活著倖存者時，讀取以下設置
    "3"
    {
        "smoker_limit"      "2"
        "boomer_limit"      "1"
        "hunter_limit"      "2"
        "spitter_limit"     "1"
        "jockey_limit"      "2"
        "charger_limit"     "2"
        "max_specials"      "3"

        "spawn_time_max"        "60.0"
        "spawn_time_min"        "50.0"

        "tank_limit"          "0"
        "tank_health"         "0"

        "witch_max_limit"           "2"
        "witch_spawn_time_max"      "150.0"
        "witch_spawn_time_min"      "150.0"

        "common_limit"        "-1"
    }

    // When there are 4 alive survivors in server
    // 當伺服器有四名活著倖存者時，讀取以下設置
    "4"
    {
        "smoker_limit"      "2"
        "boomer_limit"      "2"
        "hunter_limit"      "2"
        "spitter_limit"     "1"
        "jockey_limit"      "2"
        "charger_limit"     "2"
        "max_specials"      "4"

        "spawn_time_max"        "60.0"
        "spawn_time_min"        "50.0"

        "tank_limit"                "1"
        "tank_spawn_probability"    "1"
        "tank_health"               "0"
        "tank_spawn_final"          "0"

        "witch_max_limit"           "2"
        "witch_spawn_time_max"      "120.0"
        "witch_spawn_time_min"      "90.0"

        "common_limit"              "-1"
    }

    // When there are 5 alive survivors in server
    // 當伺服器有五名活著倖存者時，讀取以下設置
    "5"
    {
        "smoker_limit"      "2"
        "boomer_limit"      "2"
        "hunter_limit"      "2"
        "spitter_limit"     "2"
        "jockey_limit"      "2"
        "charger_limit"     "2"
        "max_specials"      "5"

        "spawn_time_max"        "60.0"
        "spawn_time_min"        "50.0"

        "tank_limit"                "1"
        "tank_spawn_probability"    "3"
        "tank_health"               "0"
        "tank_spawn_final"          "1"

        "witch_max_limit"           "3"
        "witch_spawn_time_max"      "150.0"
        "witch_spawn_time_min"      "100.0"

        "common_limit"              "-1"
    }

    // And so on....
    // 以下類推
    "6"
    {
        "smoker_limit"      "2"
        "boomer_limit"      "2"
        "hunter_limit"      "2"
        "spitter_limit"     "2"
        "jockey_limit"      "2"
        "charger_limit"     "2"
        "max_specials"      "6"

        "spawn_time_max"        "60.0"
        "spawn_time_min"        "50.0"

        "tank_limit"                "1"
        "tank_spawn_probability"    "5"
        "tank_health"               "0"
        "tank_spawn_final"          "1"

        "witch_max_limit"           "4"
        "witch_spawn_time_max"      "150.0"
        "witch_spawn_time_min"      "100.0"

        "common_limit"              "-1"

        "coop_versus_enable"            "1"
        "coop_versus_spawn_time_max"    "35.0"
        "coop_versus_spawn_time_min"    "25.0"
        "coop_versus_tank_playable"     "0"
        "coop_versus_human_limit"       "1"
    }

    "7"
    {
        "smoker_limit"      "2"
        "boomer_limit"      "2"
        "hunter_limit"      "2"
        "spitter_limit"     "2"
        "jockey_limit"      "2"
        "charger_limit"     "2"
        "max_specials"      "7"

        "spawn_time_max"        "60.0"
        "spawn_time_min"        "50.0"

        "tank_limit"                "1"
        "tank_spawn_probability"    "7"
        "tank_health"               "0"
        "tank_spawn_final"          "1"

        "witch_max_limit"           "4"
        "witch_spawn_time_max"      "150.0"
        "witch_spawn_time_min"      "100.0"

        "common_limit"              "-1"

        "coop_versus_enable"            "1"
        "coop_versus_spawn_time_max"    "35.0"
        "coop_versus_spawn_time_min"    "25.0"
        "coop_versus_tank_playable"     "0"
        "coop_versus_human_limit"       "1"
    }

    "8"
    {
        "smoker_limit"      "2"
        "boomer_limit"      "2"
        "hunter_limit"      "2"
        "spitter_limit"     "2"
        "jockey_limit"      "2"
        "charger_limit"     "2"
        "max_specials"      "8"

        "spawn_time_max"        "60.0"
        "spawn_time_min"        "50.0"

        "tank_limit"                "2"
        "tank_spawn_probability"    "7"
        "tank_health"               "0"
        "tank_spawn_final"          "1"

        "witch_max_limit"           "4"
        "witch_spawn_time_max"      "250.0"
        "witch_spawn_time_min"      "180.0"

        "common_limit"              "-1"
        
        "coop_versus_enable"            "1"
        "coop_versus_spawn_time_max"    "35.0"
        "coop_versus_spawn_time_min"    "30.0"
        "coop_versus_tank_playable"     "0"
        "coop_versus_human_limit"       "2"
    }

就修改了不需要修改坦克血量  特感上限 特感重生时间和僵尸数量

**Comment by fbef0102** [comment]
你可以用下方的按鈕拖曳文件上傳，然後具體的插件無效是什麼
沒有顯示任何提示還是不會生成任何特感？

**Comment by 2215918947** [comment]
首先是左下角的信息提示没有了   然后游戏里面没有任何僵尸和特感   无法上传cfg文件  我压缩成zip了  
[coop.zip](https://github.com/user-attachments/files/16966357/coop.zip)

**Comment by 2215918947** [comment]
KeyValues Error: LoadFromBuffer: missing { in file addons\sourcemod\data\l4dinfectedbots\coop.cfg

KeyValues Error: LoadFromBuffer: missing { in file addons\sourcemod\data\l4dinfectedbots\coop.cfg

KeyValues Error: LoadFromBuffer: missing { in file addons\sourcemod\data\l4dinfectedbots\coop.cfg

重开游戏有看到了一个错误代码  但是我没有变更过任何文件位置

**Comment by fbef0102** [comment]
將文件的編碼確認為UTF-8，可以用筆記本另存新檔的時候設定
推薦用notepad++或其他文件編輯器都可以
![202859995-2f04eee9-532e-4a5a-bacf-7f038ac79415](https://github.com/user-attachments/assets/bc8c6e15-de25-411c-9b54-9386bc1da3f7)

**Comment by 2215918947** [comment]
谢谢作者 问题解决 了
