### ISSUE TITLE
L4Dinfectedbots SI ladder function not working

### ISSUE THREAD

**Issue by Quesoteric** [fbef0102/L4D1_2-Plugins#63]
When I set this plugin up on a dedicated server, (linux machine) I noticed that the things such as infected ladders were not showing up. I did a few rollbacks and found out [this](https://github.com/fbef0102/L4D1_2-Plugins/commit/a486aaea4b7b7726b4a5e1bafff20f7bb7958c63) commit seemingly is what caused it to stop functioning. 

![20240913211204_1](https://github.com/user-attachments/assets/83f198d3-8276-4aef-a724-b9fad0d36d87)

**Comment by fbef0102** [comment]
Thanks for report
github.com/fbef0102/L4D1_2-Plugins/tree/master/l4dinfectedbots
