### ISSUE TITLE
sm_translator.sp

### ISSUE THREAD

**Issue by Neptune196** [fbef0102/L4D1_2-Plugins#67]
//// sm_translator.sp
//
// C:\Program Files (x86)\steamcmd\l4d2sv\left4dead2\addons\sourcemod\scripting\include\json\helpers\decode.inc(399) : warning 203: symbol is never used: "is_array"
//    399 |     int pos,
// --------------------^
// Code size:         69368 bytes
// Data size:         12304 bytes
// Stack/heap size:      18520 bytes
// Total requirements:  100192 bytes
//
// 1 Warning.
//
// Compilation Time: 0.2 sec
// ----------------------------------------

Press enter to exit ...

**Comment by fbef0102** [comment]
Problems from [json.inc](https://github.com/clugg/sm-json), nothing I can help
You can ingore or report
