### ISSUE TITLE
[L4D 1/2] Multi-Colors

### ISSUE THREAD

**Issue by pa4H** [fbef0102/L4D1_2-Plugins#68]
The plugin doesn't work.
Sourcemod 12, Windows

Instead of different colors, orange color everywhere.

**Comment by fbef0102** [comment]
Can you provide screenshot or image?

**Comment by pa4H** [comment]
![123](https://github.com/user-attachments/assets/c5975e01-ffc0-4d5c-b661-9d0cbd6b9e02)
Sorry for the long answer.
I took the example from [here](https://github.com/Bara/Multi-Colors)

**Comment by fbef0102** [comment]
> Thank you. I remember seeing different colors in the chat on some server a few years ago. Lots of colors. Black and purple, yellow. Doesn't this work in the current version of the engine?

I haven't seen black or purple color before

**Comment by Proaxel** [comment]
> Download my [mutil-colors fork](https://github.com/fbef0102/L4D1_2-Plugins/releases/tag/Multi-Colors).
> 
> And there are only 6 colors supported in l4d1/2, not like other source game
> 
> * {default}	(whilte)
> * {green}		(olive color)
> * {olive}		(green color)
> * {lightgreen}	(light green)
> * {red}		(red)    - There must be at least one player or bot in infected team，or red will turn into olive color
> * {blue}		(blue)   - There must be at least one player or bot in survivor team，or blue will turn into olive color
> 
> Caution
> 
> 2 of (Blue, Red, Lightgreen) colors can not be used together in one sentence

I am curious to know why these limitations exist only in L4D2, and not in any other Source game. Is it a Valve bug or intentional limitation?

**Comment by fbef0102** [comment]
> > Download my [mutil-colors fork](https://github.com/fbef0102/L4D1_2-Plugins/releases/tag/Multi-Colors).
> > And there are only 6 colors supported in l4d1/2, not like other source game
> > 
> > * {default}	(whilte)
> > * {green}		(olive color)
> > * {olive}		(green color)
> > * {lightgreen}	(light green)
> > * {red}		(red)    - There must be at least one player or bot in infected team，or red will turn into olive color
> > * {blue}		(blue)   - There must be at least one player or bot in survivor team，or blue will turn into olive color
> > 
> > Caution
> > 2 of (Blue, Red, Lightgreen) colors can not be used together in one sentence
> 
> I am curious to know why these limitations exist only in L4D2, and not in any other Source game. Is it a Valve bug or intentional limitation?

Intentional limitation, any color that isn't supported will be replaced with {green} color, which is yellow in l4d1 and l4d2
