### ISSUE TITLE
l4d_afk_commands

### ISSUE THREAD

**Issue by oethanx** [fbef0102/L4D1_2-Plugins#7]
Could you add some more conditions where the player can not go to spectator or switch team.

1- if the infected player is spawned as a special infected
2- If an infected player has pounced someone as a special infected (this can also fix several bugs related to jockey and ghost charger)

**Comment by fbef0102** [comment]
1- if the infected player is spawned as a special infected

when player enters ghost state? or spawn alive ?

**Comment by oethanx** [comment]
spawn alive

**Comment by fbef0102** [comment]
add in v3.7

// If 1, Infected player can not change team when he has pounced/ridden/charged/smoked a survivor.
l4d_afk_commands_infected_cap_block "1"

// Cold Down Time in seconds an infected player can not change team after he is spawned as a special infected. (0=off).
l4d_afk_commands_infected_spawn_cooltime_block "10.0"

**Comment by oethanx** [comment]
I'm unable to compile the plugin now:

`C:\Users\stran\Desktop\updatedafk\L4D1_2-Plugins-master\l4d_afk_commands\l4d_afk_commands.sp(220) : error 017: undefined symbol "Command_SwapTo"
C:\Users\stran\Desktop\updatedafk\L4D1_2-Plugins-master\l4d_afk_commands\l4d_afk_commands.sp(221) : error 017: undefined symbol "ForceSurvivorSuicide"
C:\Users\stran\Desktop\updatedafk\L4D1_2-Plugins-master\l4d_afk_commands\l4d_afk_commands.sp(248) : error 017: undefined symbol "GetCvars"
C:\Users\stran\Desktop\updatedafk\L4D1_2-Plugins-master\l4d_afk_commands\l4d_afk_commands.sp(250) : error 017: undefined symbol "ConVarChange_CvarGameMode"
C:\Users\stran\Desktop\updatedafk\L4D1_2-Plugins-master\l4d_afk_commands\l4d_afk_commands.sp(251) : error 017: undefined symbol "ConVarChanged_Cvars"
C:\Users\stran\Desktop\updatedafk\L4D1_2-Plugins-master\l4d_afk_commands\l4d_afk_commands.sp(252) : error 017: undefined symbol "ConVarChanged_Cvars"
C:\Users\stran\Desktop\updatedafk\L4D1_2-Plugins-master\l4d_afk_commands\l4d_afk_commands.sp(253) : error 017: undefined symbol "ConVarChanged_Cvars"
C:\Users\stran\Desktop\updatedafk\L4D1_2-Plugins-master\l4d_afk_commands\l4d_afk_commands.sp(254) : error 017: undefined symbol "ConVarChanged_Cvars"
C:\Users\stran\Desktop\updatedafk\L4D1_2-Plugins-master\l4d_afk_commands\l4d_afk_commands.sp(255) : error 017: undefined symbol "ConVarChanged_Cvars"
C:\Users\stran\Desktop\updatedafk\L4D1_2-Plugins-master\l4d_afk_commands\l4d_afk_commands.sp(256) : error 017: undefined symbol "ConVarChanged_Cvars"
C:\Users\stran\Desktop\updatedafk\L4D1_2-Plugins-master\l4d_afk_commands\l4d_afk_commands.sp(257) : error 017: undefined symbol "ConVarChanged_Cvars"
C:\Users\stran\Desktop\updatedafk\L4D1_2-Plugins-master\l4d_afk_commands\l4d_afk_commands.sp(258) : error 017: undefined symbol "ConVarChanged_Cvars"
C:\Users\stran\Desktop\updatedafk\L4D1_2-Plugins-master\l4d_afk_commands\l4d_afk_commands.sp(259) : error 017: undefined symbol "ConVarChanged_Cvars"
C:\Users\stran\Desktop\updatedafk\L4D1_2-Plugins-master\l4d_afk_commands\l4d_afk_commands.sp(260) : error 017: undefined symbol "ConVarChanged_Cvars"
C:\Users\stran\Desktop\updatedafk\L4D1_2-Plugins-master\l4d_afk_commands\l4d_afk_commands.sp(261) : error 017: undefined symbol "ConVarChanged_Cvars"
C:\Users\stran\Desktop\updatedafk\L4D1_2-Plugins-master\l4d_afk_commands\l4d_afk_commands.sp(262) : error 017: undefined symbol "ConVarChanged_Cvars"
C:\Users\stran\Desktop\updatedafk\L4D1_2-Plugins-master\l4d_afk_commands\l4d_afk_commands.sp(263) : error 017: undefined symbol "ConVarChanged_Cvars"
C:\Users\stran\Desktop\updatedafk\L4D1_2-Plugins-master\l4d_afk_commands\l4d_afk_commands.sp(264) : error 017: undefined symbol "ConVarChanged_Cvars"
C:\Users\stran\Desktop\updatedafk\L4D1_2-Plugins-master\l4d_afk_commands\l4d_afk_commands.sp(265) : error 017: undefined symbol "ConVarChanged_Cvars"
C:\Users\stran\Desktop\updatedafk\L4D1_2-Plugins-master\l4d_afk_commands\l4d_afk_commands.sp(266) : error 017: undefined symbol "ConVarChanged_Cvars"
C:\Users\stran\Desktop\updatedafk\L4D1_2-Plugins-master\l4d_afk_commands\l4d_afk_commands.sp(267) : error 017: undefined symbol "ConVarChanged_Cvars"
C:\Users\stran\Desktop\updatedafk\L4D1_2-Plugins-master\l4d_afk_commands\l4d_afk_commands.sp(268) : error 017: undefined symbol "ConVarChanged_Cvars"
C:\Users\stran\Desktop\updatedafk\L4D1_2-Plugins-master\l4d_afk_commands\l4d_afk_commands.sp(269) : error 017: undefined symbol "ConVarChanged_Cvars"
C:\Users\stran\Desktop\updatedafk\L4D1_2-Plugins-master\l4d_afk_commands\l4d_afk_commands.sp(271) : error 017: undefined symbol "OnWitchWokeup"
C:\Users\stran\Desktop\updatedafk\L4D1_2-Plugins-master\l4d_afk_commands\l4d_afk_commands.sp(277) : error 017: undefined symbol "Event_PlayerDeath"
C:\Users\stran\Desktop\updatedafk\L4D1_2-Plugins-master\l4d_afk_commands\l4d_afk_commands.sp(278) : error 017: undefined symbol "Event_PlayerChangeTeam"`
