### ISSUE TITLE
helpmenu

### ISSUE THREAD

**Issue by oethanx** [fbef0102/L4D1_2-Plugins#8]
Request: A chat command to disable the auto menu from showing to players every time instead of a menu item, with translation.

**Comment by fbef0102** [comment]
**Disable the help menu forever.
	"sm_helpoff"

**Enable the help menu next time."
	"sm_helpon"

**Comment by oethanx** [comment]
the enabled and disabled text don't work properly it says "auto menu is t" instead of "auto menu is disabled/enabled"

**Comment by fbef0102** [comment]
![未命名](https://user-images.githubusercontent.com/12229810/133246313-2c65fb00-68bb-4569-8357-2cf4e1d60bbb.jpg)
huh?
